---
abstract: 'read, eval, print, loop, yay!'
author:
  - 'Jesse Luehrs <doy@tozt.net>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 1
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Reply
no_index:
  package:
    - Reply::Plugin::Defaults
    - Reply::Util
recommends:
  App::Nopaste: 0
  B::Keywords: 0
  Carp::Always: 0
  Class::Refresh: 0.05
  Data::Dump: 0
  Data::Printer: 0
  Proc::InvokeEditor: 0
  Term::ReadLine::Gnu: 0
requires:
  Config::INI::Reader::Ordered: 0
  Data::Dumper: 0
  Devel::LexAlias: 0
  Eval::Closure: 0.09
  Exporter: 0
  File::HomeDir: 0
  File::Spec: 0
  Getopt::Long: 2.36
  Module::Runtime: 0
  Package::Stash: 0
  PadWalker: 0
  Scalar::Util: 0
  Term::ANSIColor: 0
  Term::ReadLine: 0
  Time::HiRes: 0
  Try::Tiny: 0
  base: 0
  overload: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/doy/reply/issues
  homepage: http://metacpan.org/release/Reply
  repository: git://github.com/doy/reply.git
version: 0.30
x_Dist_Zilla:
  perl:
    version: 5.018000
  plugins:
    -
      class: Dist::Zilla::Plugin::FileFinder::Filter
      name: WeaverFiles
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: test
          type: requires
      name: '@DOY/TestMoreDoneTesting'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@DOY/GatherDir'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@DOY/PruneCruft'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@DOY/ManifestSkip'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@DOY/MetaYAML'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::License
      name: '@DOY/License'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@DOY/Readme'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      name: '@DOY/RunExtraTests'
      version: 0.011
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@DOY/ExecDir'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@DOY/ShareDir'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@DOY/MakeMaker'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@DOY/Manifest'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@DOY/TestRelease'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@DOY/ConfirmRelease'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@DOY/MetaConfig'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@DOY/MetaJSON'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@DOY/NextRelease'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: '@DOY/CheckChangesHasContent'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@DOY/PkgVersion'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@DOY/Authority'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@DOY/PodCoverageTests'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@DOY/PodSyntaxTests'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@DOY/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@DOY/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: '@DOY/Test::Compile'
      version: 2.002
    -
      class: Dist::Zilla::Plugin::Metadata
      name: '@DOY/Metadata'
      version: 3.03
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: '@DOY/MetaResources'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@DOY/Git::Check'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@DOY/Git::Commit'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@DOY/Git::Tag'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@DOY/Git::NextVersion'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@DOY/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@DOY/UploadToCPAN'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::ContributorsFromGit
      name: ContributorsFromGit
      version: 0.006
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: MetaNoIndex
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: recommends
      name: RuntimeRecommends
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::OSPrereqs
      config:
        Dist::Zilla::Plugin::OSPrereqs:
          os: MSWin32
      name: MSWin32
      version: 0.003
    -
      class: Dist::Zilla::Plugin::PerlVersionPrereqs
      config:
        Dist::Zilla::Plugin::PerlVersionPrereqs:
          perl_version: 5.010
      name: 5.010
      version: 0.01
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300034
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300034
x_authority: cpan:DOY
x_contributors:
  - "Arthur Axel 'fREW' Schmidt <frioux@gmail.com>"
  - 'Kosuke Asami <tfortress58@gmail.com>'
  - 'Michael Reddick <michael.reddick@gmail.com>'
  - 'Sawyer X <xsawyerx@cpan.org>'
  - 'Shawn M Moore <code@sartak.org>'
  - 'Stanislaw Pusep <creaktive@gmail.com>'
  - 'Toby Inkster <mail@tobyinkster.co.uk>'
